[project]
name = "astrobro"
version = "1.0.0"
description = "your pocket astrologer ðŸ’«"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "authlib",
    "natal",
    "openai",
    "st-screenwidth-detector",
    "streamlit",
    "streamlit-shortcuts",
]

[tool.ruff]
isort.no-sections = true
line-length = 100
extend-ignore = ["E203", "E402", "E501", "E712", "F401", "F811"]

[tool.uv.sources]
natal = { git = "https://github.com/hoishing/natal" }

[dependency-groups]
dev = ["ipykernel", "pytest", "watchdog"]
