#:schema none

[server]
enableStaticServing = true
runOnSave = true

[client]
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#ffbf00"
backgroundColor = "#212529"
secondaryBackgroundColor = "#343a40"
baseRadius = "large"

[browser]
gatherUsageStats = false
